### ISSUE TITLE
File Menu Not Show Popup In Locale Indonesia

### ISSUE THREAD

**Issue by syifarahmat** [syncfusion/ej2-locale#161]
https://github.com/syncfusion/ej2-locale/blob/8e773d2f17e8fd30cb88d5bcfdb70eb7a0626502/src/id.json#LL212C10-L212C21

![image](https://github.com/syncfusion/ej2-locale/assets/11779955/ee538afd-188b-4a0a-9af1-c9a16802cadf)

**Comment by sangeetha-priya-M** [comment]
We have rendered the spreadsheet using Indonesian local culture text, and the File menu popup opened properly on our end. You can find the screenshot and sample link below.

![image](https://github.com/syncfusion/ej2-locale/assets/92911656/d662b7c4-b9e9-4025-939e-7a9da46b6d47)


Sample Link: https://stackblitz.com/edit/zpr86p-5gh5xn?file=index.ts,locale-text.json,index.html


Please check the above link, replicate your issue in the above sample, and send it back to us if you are still getting the same issue or need further assistance on this.

**Comment by syifarahmat** [comment]
> We have rendered the spreadsheet using Indonesian local culture text, and the File menu popup opened properly on our end. You can find the screenshot and sample link below.
> 
> ![image](https://user-images.githubusercontent.com/92911656/239897243-d662b7c4-b9e9-4025-939e-7a9da46b6d47.png)
> 
> Sample Link: https://stackblitz.com/edit/zpr86p-5gh5xn?file=index.ts,locale-text.json,index.html
> 
> Please check the above link, replicate your issue in the above sample, and send it back to us if you are still getting the same issue or need further assistance on this.

Ohh... thanks, I'm not careful 👌👌👌
