### ISSUE TITLE
Alphabetically Sorting

### ISSUE THREAD

**Issue by HSolis95** [syncfusion/ej2-locale#178]
When comparing between two languages is easier when the Keys and their nodes are alpha sorted, by doing this I was able to determine wich keys were missing in my language file.

Also I think could be useful for some people to have an empty version of the dictionary

**Comment by PiramanayagamSyncfusion** [comment]
Dear Customer,

Sorry for the delay.

We have considered this feature (Provide locale alphabet sort support) at our end. You can track this feature status in the below feedback.
https://www.syncfusion.com/feedback/51820/need-to-provide-locale-alphabet-sort-support

Usually, Syncfusion will plan and implement the features based on feature rank, customer requested count, and volume wish-list. We will implement and include this feature in any of our upcoming releases.

Regards,
Piramanayagam R
