### ISSUE TITLE
translate error

### ISSUE THREAD

**Issue by Hankscr459** [syncfusion/ej2-locale#180]
"{0}頁中的{0}頁"

should be

"第{0}頁／共{1}頁"

https://github.com/syncfusion/ej2-locale/blob/master/src/zh.json#L135

**Comment by PiramanayagamSyncfusion** [comment]
Hi @Hankscr459 ,

Sorry for the delay. 

We have moved your changes in the following PR.
https://github.com/syncfusion/ej2-locale/pull/190
So, we have closed this issue.

Regards,
Piramanayagam R
