### ISSUE TITLE
Request for tagging release versions

### ISSUE THREAD

**Issue by michaelmairegger** [syncfusion/ej2-locale#207]
Would it be possible to tag each syncfusion realease to allow better comparison about what changed. Until now I have to look into commit history in oder to find the diffs between each version. It would be far more convinient to have tags in oder to use the compare feature of github.

**Comment by Mohamed7Imran** [comment]
Hi @michaelmairegger , 

Thank you for reaching out and providing your feedback. We are pleased to inform you that we will incorporate tagging for each Syncfusion version in our upcoming releases to have a streamlined process for comparing changes between versions. 

Regards,
Mohamed

**Comment by Mohamed7Imran** [comment]
Hi @michaelmairegger ,

We are pleased to inform you that we have provided release tags for our latest releases, and we will continue to include them for all upcoming releases. This will make it easier to track changes and to have a streamlined process for comparing changes between versions.

Please feel free to get in touch with us if you need any further assistance.

Regards,
Mohamed
