### ISSUE TITLE
Spanish messages were replaced by english messages

### ISSUE THREAD

**Issue by cristhiank** [syncfusion/ej2-locale#25]
The Spanish messages were replaced by English messages in the latest update:

https://github.com/syncfusion/ej2-locale/blob/master/src/es.json

**Comment by jesusarockias** [comment]
Hi @cristhiank ,

We have fixed the reported issue and refreshed the same in github repository. Now, we ask you to check this in your end and revert back if you still experience the same issue.

Link: https://github.com/syncfusion/ej2-locale/blob/master/src/es.json

Regards,
Jesus Arockia Sankaran S

**Comment by cristhiank** [comment]
Thanks, that’s great. I already reverted my dependency because I am using the npmjs.com package. I will update when a new version is pushed to the npm registry.

**Comment by Saranya13** [comment]
Hi @cristhiank ,

We have published the locale package in npmjs. Now, we ask you to check this in your end and revert back, if you have any concerns.

Link: https://www.npmjs.com/package/@syncfusion/ej2-locale

Regards,
Saranya M

**Comment by cristhiank** [comment]
Cool, I will do the upgrade today and will let you know. Thanks!

**Comment by cristhiank** [comment]
Thanks, I confirm the messages are ok now.
