### ISSUE TITLE
Set localization globally

### ISSUE THREAD

**Issue by ltomczok** [syncfusion/ej2-locale#3]
Hey,
I have a question, where to put this code in case of ASP.NET Core application? In _Layout.cshtml? I would like to set the localization globally for the entire application.

`var L10n = new ej.base.L10();
var setCulture = new ej.base.setCulture();
L10n.load({
    var ajax = new ej.base.Ajax('/src/ar-AE.json', 'GET', true);
    ajax.send()
});
setCulture(‘ar-AE’);`

**Comment by ajithr** [comment]
Hi @ltomczok ,

Thanks for your interest in Syncfusion products.

The previously provided code snippets in the ReadMe file is not correct one and we have modified it now. Please refer the below code snippet and use it to set the localization globally for the entire application from _Layout.cshtml file.

**[code example] [_Layout.cshtml]**
```
<head>
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script>
      ej.base.setCulture('ar-AE');
                  var val, ajax;
                  var ajax = new ej.base.Ajax('/src/ar-AE.json', 'GET', true);
                  ajax.onSuccess = function (value) {        
                   //Assigning locale text value for Essential JS 2 components
        ej.base.L10n.load(value);
      };
      ajax.send();
    </script>
</head>
```

Please let us know if you need any further assistance on this.

Regards,
Ajith R
