### ISSUE TITLE
File zh.json is a wrong file

### ISSUE THREAD

**Issue by JoJoe88** [syncfusion/ej2-locale#36]
zh.json is same with vi.json, and its not Chinese. maybe you put the wrong file of zh.json

**Comment by icsilambarasan** [comment]
Hi @JoJoe88,

Sorry for the inconvenience. We have modified the Chinese locale 'zh' file and changes have been included.

Please check now and revert us if you faced any issues.

**Comment by JoJoe88** [comment]
Thanks. but there too many translation errors in zh.json. 
eg:
`       "schedule": {
            "day": "報告清單",
            "week": "您確定要刪除此報告嗎？",
            "workWeek": "找不到報告！",
            "month": "酒吧",
            "agenda": "線",
            "weekAgenda": "區域",`
the correct translation are:
 '      "schedule": {
            "day": "日",
            "week": "星期",
            "workWeek": "工作周",
            "month": "月",
            "agenda": "日程",
            "weekAgenda": 周计划",'
Thanks again

**Comment by icsilambarasan** [comment]
Hi @JoJoe88 

We would like to let you know that we have provided these locale files which are translated using google translator. We will include your above translated correction and it’ll be available within our upcoming 2019 Volume 4 SP release. We appreciate your patience until then.

Also, you can contribute for locale text correction by making the pull request with your changes. We will check and merge your request.

**Comment by jesusarockias** [comment]
HI @JoJoe88  ,

We have resolved the translation issues for Chinese culture and the package has been refreshed with changes in npm registry. 

Please feel free to report any other translation issue if you find that is greatly appreciated.
