### ISSUE TITLE
Can't change "Draw-hand Signature"  value in locales

### ISSUE THREAD

**Issue by kopkaa** [syncfusion/ej2-locale#90]
I am using pdfViewer component, I need tot translate `pdfViewer['Draw-hand Signature']` , but when I do, the signatures doesn't show in signature field when signing.

**Comment by Vasugisivajothi** [comment]
Hi kopkaa,

We have resolved the locale issues in the latest version v20.1.0.50. Kindly upgrade to that version to resolve the issues. We have shared the sample for your reference, please refer to the below link.

Sample: https://stackblitz.com/edit/dtctsb?file=index.js

Kindly try this and let us know if you have any concerns about this.

Regards,
Vasugi.

**Comment by syncsiva** [comment]
This issue has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
